{% set version = "0.1.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-aws.ec2metadata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/aws.ec2metadata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/aws.ec2metadata/aws.ec2metadata_{{ version }}.tar.gz
  sha256: f647930d9b5eb0db3b277894a96cd11bc3f0d5fc1a100d6a2a51b069fe7c9955

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-curl
    - r-jsonlite
  run:
    - r-base
    - r-curl
    - r-jsonlite

test:
  commands:
    - $R -e "library('aws.ec2metadata')"           # [not win]
    - "\"%R%\" -e \"library('aws.ec2metadata')\""  # [win]

about:
  home: https://github.com/cloudyr/aws.ec2metadata
  license: GPL (>= 2)
  summary: Retrieve Amazon EC2 instance metadata from within the running instance.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: aws.ec2metadata
# Type: Package
# Title: Get EC2 Instance Metadata
# Version: 0.1.5
# Date: 2018-07-26
# Authors@R: c(person("Thomas J.", "Leeper", role = c("aut", "cre"), email = "thosjleeper@gmail.com", comment = c(ORCID = "0000-0003-4097-6326")))
# Description: Retrieve Amazon EC2 instance metadata from within the running instance.
# License: GPL (>= 2)
# URL: https://github.com/cloudyr/aws.ec2metadata
# BugReports: https://github.com/cloudyr/aws.ec2metadata/issues
# Imports: curl, jsonlite
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-07-26 11:51:21 UTC; THOMAS
# Author: Thomas J. Leeper [aut, cre] (<https://orcid.org/0000-0003-4097-6326>)
# Maintainer: Thomas J. Leeper <thosjleeper@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-07-26 12:20:03 UTC
