# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "C8VSgbaKylOi4ljbA0xahupZ9hDs66bHh91wAXAl7TN/QMb60XDqYDjqxjYSjgQPa5hKAHpA/n7f806Q81AWRWWfFTNg1/+IIdk3WEKMfHetPJOBPSqBNcpDyzCusmvzjST75cPUMFsjrWpo/tYyOeM8dhhi0AZALO4VE+Zf8RHbflkbLBDIkO6Twdj2tH1zVE3HEmot9XtUX1++zVBD3AHpMm9QqIsHS7mZsW+PUYdMRO9Lty2FBjbZz4KwbH+a1PoO0gXz+SsKUzorta0yB6xRFQP5qcb8eN6cM5hR9M4SR8MvlcKt7643Z2TSIXBajyHnRwfGXNOfuUsvzlRQml/XIrMlj/IKIkB6OERDhYvoqoVtzMo8ANKOGOkz7P/TW/1Y2Azd0Q45x4Mz39dBgGvghPmhb71/Z+DW8YCO938Bn2Je0nx5oRdJFkE8PjGDH5HcsXRIrlDXgJojQ7TkwctXbeuiXq8poIiksjHU14B6RQBmLHJBDSnx2Zyh4FkK3e2K3UuAsKNpoWCoNIHrlkRGzXen+S/EYCchOXdtrrX/84apkjNYV51+YCQYOxFHfdaQZaHexbSSgM9cxQYHep90szmxTUh7/kbMSvMtSTjNicLGVmQ0qq6kGzRQvaQOrG934u8eG5tSAD/W4U9KkANcqlWBXYyr2VC1TRRu0ZM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
