appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: C8VSgbaKylOi4ljbA0xahupZ9hDs66bHh91wAXAl7TN/QMb60XDqYDjqxjYSjgQPa5hKAHpA/n7f806Q81AWRWWfFTNg1/+IIdk3WEKMfHetPJOBPSqBNcpDyzCusmvzjST75cPUMFsjrWpo/tYyOeM8dhhi0AZALO4VE+Zf8RHbflkbLBDIkO6Twdj2tH1zVE3HEmot9XtUX1++zVBD3AHpMm9QqIsHS7mZsW+PUYdMRO9Lty2FBjbZz4KwbH+a1PoO0gXz+SsKUzorta0yB6xRFQP5qcb8eN6cM5hR9M4SR8MvlcKt7643Z2TSIXBajyHnRwfGXNOfuUsvzlRQml/XIrMlj/IKIkB6OERDhYvoqoVtzMo8ANKOGOkz7P/TW/1Y2Azd0Q45x4Mz39dBgGvghPmhb71/Z+DW8YCO938Bn2Je0nx5oRdJFkE8PjGDH5HcsXRIrlDXgJojQ7TkwctXbeuiXq8poIiksjHU14B6RQBmLHJBDSnx2Zyh4FkK3e2K3UuAsKNpoWCoNIHrlkRGzXen+S/EYCchOXdtrrX/84apkjNYV51+YCQYOxFHfdaQZaHexbSSgM9cxQYHep90szmxTUh7/kbMSvMtSTjNicLGVmQ0qq6kGzRQvaQOrG934u8eG5tSAD/W4U9KkANcqlWBXYyr2VC1TRRu0ZM=}
