travis:
  secure:
    BINSTAR_TOKEN: k5ndIFcjvlNzdPxKYkDu8L2uXw7Uvi1JjZkZbeFivHU8K/VQXFNxWqSdHd+dI1BAypVbT746BLETZLjmdmg+gTv3C6X6q65qxHgHnXa19vcrVwWFXAEhInXB9WMR00ju0cAOH9k7cYBLnUlxhKkaa2jwYCtpCFJ+RvtOflwCMvYU09Bjg8Cq5j1AVXAE4uzCNgxqsJW1PYfv+b0TwVQ5sTk/wgOFqIk8IC97c+UymybCeAK6folviAAuHgW54bPUv5XICY6cU7a8bdnLFNLz/ZvkarsPrzayJLRfL85cjYcV+mEcMqNDPE2amGdH385mLetIJvvu5j80E8cafF3HILT+WoSeEm8MqInQdszr2/9SRH20/73T1xCcD1RJ5AN66zmRv/s8GoDUnjyObpboHVrdL/Q7mBSZvuzwhuvk3ZCiOMX9lstX3eQQZKultnmTjKERKDF3qYUDhenWzrUTKRzaAn3Cya2rsKXiiqC6J72RDnC57BRmdOAeU0mG+lbm8myhkqIZGUTDTaPqldvCYdK2JXswWo+kpYj1u+tQUOnM78LnAX6RaGqvk+cX+DxZ8XE2Ct6qWBjRmg+7PW68Zes5piFwv7DPO5liVvNr2jo0HHuexRBiAOWPUKqANjPh2DDPVs0vBxf/EXXGjSmzccshl3eifX/DkZtHAl7fAUY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
